server:
  port: 9090
spring:
  profiles:
    active: develop
  batch:
    job:
      names: ${job.name:NONE}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/coupon?serverTimezone=UTC
    username: root
    password: password
  jpa:
    open-in-view: false
    generate-ddl: false
    ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
        descriptor:
          sql: true
      show-sql: true
logging:
  config: classpath:logback.xml
  pattern:
    console: '%-5level %d{yyyy-MM-dd HH:mm:ss} [%thread] %class{36}.%method:%line - %msg%n'
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
    com:
      gavinkim: debug
#    root: info

jwt:
  token:
    secret: wokaa^*saowek